export const popularCarBrands = [
  { id: 1, name: "Toyota" },
  { id: 2, name: "Ford" },
  { id: 3, name: "Honda" },
  { id: 4, name: "Chevrolet" },
  { id: 5, name: "Mercedes-Benz" },
  { id: 6, name: "BMW" },
  { id: 7, name: "Volkswagen" },
  { id: 8, name: "Audi" },
  { id: 9, name: "Tesla" },
  { id: 10, name: "Nissan" },
];

export const allCarBrands = [
  { id: 1, name: "All" },
  { id: 2, name: "Toyota" },
  { id: 3, name: "Ford" },
  { id: 4, name: "Honda" },
  { id: 5, name: "Chevrolet" },
  { id: 6, name: "Mercedes-Benz" },
  { id: 7, name: "BMW" },
  { id: 8, name: "Volkswagen" },
  { id: 9, name: "Audi" },
  { id: 10, name: "Tesla" },
  { id: 11, name: "Nissan" },
  { id: 12, name: "Hyundai" },
  { id: 13, name: "Kia" },
  { id: 14, name: "Porsche" },
  { id: 15, name: "Subaru" },
  { id: 16, name: "Mazda" },
  { id: 17, name: "Jaguar" },
  { id: 18, name: "Land Rover" },
  { id: 19, name: "Lexus" },
  { id: 20, name: "Ferrari" },
  { id: 21, name: "Lamborghini" },
  { id: 22, name: "Maserati" },
  { id: 23, name: "Bugatti" },
  { id: 24, name: "Peugeot" },
  { id: 25, name: "Renault" },
  { id: 26, name: "Fiat" },
  { id: 27, name: "Alfa Romeo" },
  { id: 28, name: "Opel" },
  { id: 29, name: "Skoda" },
  { id: 30, name: "Citroën" },
  { id: 31, name: "Mitsubishi" },
  { id: 32, name: "Chrysler" },
  { id: 33, name: "Dodge" },
  { id: 34, name: "Jeep" },
  { id: 35, name: "Ram" },
  { id: 36, name: "Acura" },
  { id: 37, name: "Infiniti" },
  { id: 38, name: "Suzuki" },
  { id: 39, name: "Volvo" },
  { id: 40, name: "Saab" },
  { id: 41, name: "Bentley" },
  { id: 42, name: "Rolls-Royce" },
  { id: 43, name: "Aston Martin" },
  { id: 44, name: "Genesis" },
  { id: 45, name: "McLaren" },
  { id: 46, name: "Dacia" },
];

export const carFuel = [
  { id: 1, name: "All" },
  { id: 2, name: "Petrol" },
  { id: 3, name: "Diesel" },
  { id: 4, name: "Electric" },
  { id: 5, name: "Hybrid" },
  { id: 6, name: "Gas" },
];

export const carTransmissions = [
  { id: 1, name: "All" },
  { id: 2, name: "Manual" },
  { id: 3, name: "Automatic" },
];
